# Generated by Django 5.1.2 on 2024-11-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority']},
        ),
    ]
