# Generated by Django 5.1.2 on 2024-11-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority']},
        ),
    ]
